# Generated by Django 5.2 on 2025-04-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enter a valid YouTube video URL', verbose_name='YouTube URL')),
                ('youtube_id', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='YouTube ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Video Title')),
                ('description', models.TextField(blank=True, verbose_name='Video Description')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('channel_name', models.CharField(blank=True, max_length=255, verbose_name='Channel Name')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publication Date')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='videos_vide_status_e696e3_idx'), models.Index(fields=['youtube_id'], name='videos_vide_youtube_f66dc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Transcript Content')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Transcript Language')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='Auto-generated Transcript')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='videos.video', verbose_name='Related Video')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
            },
        ),
    ]
