# Generated by Django 5.2 on 2025-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='beautified_content',
            field=models.TextField(blank=True, verbose_name='Beautified Transcript Content'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='raw_transcript_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Raw Transcript Data'),
        ),
    ]
