# Generated by Django 5.2 on 2025-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_transcript_beautified_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Transcript Summary'),
        ),
    ]
