# Generated by Django 5.2 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_transcript_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing Completed At'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processing Started At'),
        ),
    ]
